services:
  dnsmasq:
    image: jpillora/dnsmasq
    container_name: dnsmasq-ubuntu-local
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "5380:8080"       # Web UI
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf:ro
      - ./logs:/var/log:rw
    restart: always
    cap_add:
      - NET_ADMIN
